#!/bin/sh

# Initialise Vbuddy connection
~/Documents/iac/lab0-devtools/tools/attach_usb.sh

# cleanup
rm -rf obj_dir
rm -f counter.vcd

# run Verilator to translate Verilog into C++ including C++ testbench
verilator -Wall --cc --trace top.sv f1_fsm.sv clktick.sv  --exe clktick_tb.cpp --top-module top

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop  # Capital 'V' in 'Vtop.mk'

# run executable simulation file
obj_dir/Vtop  # Capital 'V' in 'Vtop'

#source ./doit.sh